// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trasaction.proto
// Protobuf Java Version: 4.27.2

package com.example.demo.message;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sourceName = 1;</code>
   * @return The sourceName.
   */
  java.lang.String getSourceName();
  /**
   * <code>string sourceName = 1;</code>
   * @return The bytes for sourceName.
   */
  com.google.protobuf.ByteString
      getSourceNameBytes();

  /**
   * <code>string sourceNumDoc = 2;</code>
   * @return The sourceNumDoc.
   */
  java.lang.String getSourceNumDoc();
  /**
   * <code>string sourceNumDoc = 2;</code>
   * @return The bytes for sourceNumDoc.
   */
  com.google.protobuf.ByteString
      getSourceNumDocBytes();

  /**
   * <code>string destinationName = 3;</code>
   * @return The destinationName.
   */
  java.lang.String getDestinationName();
  /**
   * <code>string destinationName = 3;</code>
   * @return The bytes for destinationName.
   */
  com.google.protobuf.ByteString
      getDestinationNameBytes();

  /**
   * <code>string destinationNumDoc = 4;</code>
   * @return The destinationNumDoc.
   */
  java.lang.String getDestinationNumDoc();
  /**
   * <code>string destinationNumDoc = 4;</code>
   * @return The bytes for destinationNumDoc.
   */
  com.google.protobuf.ByteString
      getDestinationNumDocBytes();

  /**
   * <code>string transactionValue = 5;</code>
   * @return The transactionValue.
   */
  java.lang.String getTransactionValue();
  /**
   * <code>string transactionValue = 5;</code>
   * @return The bytes for transactionValue.
   */
  com.google.protobuf.ByteString
      getTransactionValueBytes();
}
