// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trasaction.proto
// Protobuf Java Version: 4.27.2

package com.example.demo.message;

public interface TransactionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.TransactionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string statusCode = 1;</code>
   * @return The statusCode.
   */
  java.lang.String getStatusCode();
  /**
   * <code>string statusCode = 1;</code>
   * @return The bytes for statusCode.
   */
  com.google.protobuf.ByteString
      getStatusCodeBytes();
}
