// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trasaction.proto
// Protobuf Java Version: 4.27.2

package com.example.demo.message;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code message.Transaction}
 */
public final class Transaction extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:message.Transaction)
    TransactionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Transaction.class.getName());
  }
  // Use Transaction.newBuilder() to construct.
  private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Transaction() {
    sourceName_ = "";
    sourceNumDoc_ = "";
    destinationName_ = "";
    destinationNumDoc_ = "";
    transactionValue_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.message.TransactionProto.internal_static_message_Transaction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.message.TransactionProto.internal_static_message_Transaction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.message.Transaction.class, com.example.demo.message.Transaction.Builder.class);
  }

  public static final int SOURCENAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceName_ = "";
  /**
   * <code>string sourceName = 1;</code>
   * @return The sourceName.
   */
  @java.lang.Override
  public java.lang.String getSourceName() {
    java.lang.Object ref = sourceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceName_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceName = 1;</code>
   * @return The bytes for sourceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceNameBytes() {
    java.lang.Object ref = sourceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCENUMDOC_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceNumDoc_ = "";
  /**
   * <code>string sourceNumDoc = 2;</code>
   * @return The sourceNumDoc.
   */
  @java.lang.Override
  public java.lang.String getSourceNumDoc() {
    java.lang.Object ref = sourceNumDoc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceNumDoc_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceNumDoc = 2;</code>
   * @return The bytes for sourceNumDoc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceNumDocBytes() {
    java.lang.Object ref = sourceNumDoc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceNumDoc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATIONNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object destinationName_ = "";
  /**
   * <code>string destinationName = 3;</code>
   * @return The destinationName.
   */
  @java.lang.Override
  public java.lang.String getDestinationName() {
    java.lang.Object ref = destinationName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationName_ = s;
      return s;
    }
  }
  /**
   * <code>string destinationName = 3;</code>
   * @return The bytes for destinationName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationNameBytes() {
    java.lang.Object ref = destinationName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATIONNUMDOC_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object destinationNumDoc_ = "";
  /**
   * <code>string destinationNumDoc = 4;</code>
   * @return The destinationNumDoc.
   */
  @java.lang.Override
  public java.lang.String getDestinationNumDoc() {
    java.lang.Object ref = destinationNumDoc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationNumDoc_ = s;
      return s;
    }
  }
  /**
   * <code>string destinationNumDoc = 4;</code>
   * @return The bytes for destinationNumDoc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationNumDocBytes() {
    java.lang.Object ref = destinationNumDoc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationNumDoc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONVALUE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transactionValue_ = "";
  /**
   * <code>string transactionValue = 5;</code>
   * @return The transactionValue.
   */
  @java.lang.Override
  public java.lang.String getTransactionValue() {
    java.lang.Object ref = transactionValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionValue_ = s;
      return s;
    }
  }
  /**
   * <code>string transactionValue = 5;</code>
   * @return The bytes for transactionValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionValueBytes() {
    java.lang.Object ref = transactionValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sourceName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceNumDoc_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sourceNumDoc_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinationName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, destinationName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinationNumDoc_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, destinationNumDoc_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionValue_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, transactionValue_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sourceName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceNumDoc_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sourceNumDoc_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinationName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, destinationName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destinationNumDoc_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, destinationNumDoc_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionValue_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, transactionValue_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.message.Transaction)) {
      return super.equals(obj);
    }
    com.example.demo.message.Transaction other = (com.example.demo.message.Transaction) obj;

    if (!getSourceName()
        .equals(other.getSourceName())) return false;
    if (!getSourceNumDoc()
        .equals(other.getSourceNumDoc())) return false;
    if (!getDestinationName()
        .equals(other.getDestinationName())) return false;
    if (!getDestinationNumDoc()
        .equals(other.getDestinationNumDoc())) return false;
    if (!getTransactionValue()
        .equals(other.getTransactionValue())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCENAME_FIELD_NUMBER;
    hash = (53 * hash) + getSourceName().hashCode();
    hash = (37 * hash) + SOURCENUMDOC_FIELD_NUMBER;
    hash = (53 * hash) + getSourceNumDoc().hashCode();
    hash = (37 * hash) + DESTINATIONNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationName().hashCode();
    hash = (37 * hash) + DESTINATIONNUMDOC_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationNumDoc().hashCode();
    hash = (37 * hash) + TRANSACTIONVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionValue().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.message.Transaction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.message.Transaction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.message.Transaction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.message.Transaction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.message.Transaction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.message.Transaction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.message.Transaction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.message.Transaction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.message.Transaction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.message.Transaction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.message.Transaction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.message.Transaction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.message.Transaction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code message.Transaction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:message.Transaction)
      com.example.demo.message.TransactionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.message.TransactionProto.internal_static_message_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.message.TransactionProto.internal_static_message_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.message.Transaction.class, com.example.demo.message.Transaction.Builder.class);
    }

    // Construct using com.example.demo.message.Transaction.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sourceName_ = "";
      sourceNumDoc_ = "";
      destinationName_ = "";
      destinationNumDoc_ = "";
      transactionValue_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.message.TransactionProto.internal_static_message_Transaction_descriptor;
    }

    @java.lang.Override
    public com.example.demo.message.Transaction getDefaultInstanceForType() {
      return com.example.demo.message.Transaction.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.message.Transaction build() {
      com.example.demo.message.Transaction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.message.Transaction buildPartial() {
      com.example.demo.message.Transaction result = new com.example.demo.message.Transaction(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.message.Transaction result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sourceName_ = sourceName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourceNumDoc_ = sourceNumDoc_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.destinationName_ = destinationName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.destinationNumDoc_ = destinationNumDoc_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.transactionValue_ = transactionValue_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.message.Transaction) {
        return mergeFrom((com.example.demo.message.Transaction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.message.Transaction other) {
      if (other == com.example.demo.message.Transaction.getDefaultInstance()) return this;
      if (!other.getSourceName().isEmpty()) {
        sourceName_ = other.sourceName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSourceNumDoc().isEmpty()) {
        sourceNumDoc_ = other.sourceNumDoc_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDestinationName().isEmpty()) {
        destinationName_ = other.destinationName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDestinationNumDoc().isEmpty()) {
        destinationNumDoc_ = other.destinationNumDoc_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTransactionValue().isEmpty()) {
        transactionValue_ = other.transactionValue_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sourceName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sourceNumDoc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              destinationName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              destinationNumDoc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              transactionValue_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sourceName_ = "";
    /**
     * <code>string sourceName = 1;</code>
     * @return The sourceName.
     */
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceName = 1;</code>
     * @return The bytes for sourceName.
     */
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceName = 1;</code>
     * @param value The sourceName to set.
     * @return This builder for chaining.
     */
    public Builder setSourceName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceName() {
      sourceName_ = getDefaultInstance().getSourceName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sourceName = 1;</code>
     * @param value The bytes for sourceName to set.
     * @return This builder for chaining.
     */
    public Builder setSourceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sourceNumDoc_ = "";
    /**
     * <code>string sourceNumDoc = 2;</code>
     * @return The sourceNumDoc.
     */
    public java.lang.String getSourceNumDoc() {
      java.lang.Object ref = sourceNumDoc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceNumDoc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceNumDoc = 2;</code>
     * @return The bytes for sourceNumDoc.
     */
    public com.google.protobuf.ByteString
        getSourceNumDocBytes() {
      java.lang.Object ref = sourceNumDoc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceNumDoc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceNumDoc = 2;</code>
     * @param value The sourceNumDoc to set.
     * @return This builder for chaining.
     */
    public Builder setSourceNumDoc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceNumDoc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceNumDoc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceNumDoc() {
      sourceNumDoc_ = getDefaultInstance().getSourceNumDoc();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string sourceNumDoc = 2;</code>
     * @param value The bytes for sourceNumDoc to set.
     * @return This builder for chaining.
     */
    public Builder setSourceNumDocBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceNumDoc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object destinationName_ = "";
    /**
     * <code>string destinationName = 3;</code>
     * @return The destinationName.
     */
    public java.lang.String getDestinationName() {
      java.lang.Object ref = destinationName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destinationName = 3;</code>
     * @return The bytes for destinationName.
     */
    public com.google.protobuf.ByteString
        getDestinationNameBytes() {
      java.lang.Object ref = destinationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destinationName = 3;</code>
     * @param value The destinationName to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      destinationName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string destinationName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationName() {
      destinationName_ = getDefaultInstance().getDestinationName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string destinationName = 3;</code>
     * @param value The bytes for destinationName to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      destinationName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object destinationNumDoc_ = "";
    /**
     * <code>string destinationNumDoc = 4;</code>
     * @return The destinationNumDoc.
     */
    public java.lang.String getDestinationNumDoc() {
      java.lang.Object ref = destinationNumDoc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationNumDoc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destinationNumDoc = 4;</code>
     * @return The bytes for destinationNumDoc.
     */
    public com.google.protobuf.ByteString
        getDestinationNumDocBytes() {
      java.lang.Object ref = destinationNumDoc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationNumDoc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destinationNumDoc = 4;</code>
     * @param value The destinationNumDoc to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationNumDoc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      destinationNumDoc_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string destinationNumDoc = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationNumDoc() {
      destinationNumDoc_ = getDefaultInstance().getDestinationNumDoc();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string destinationNumDoc = 4;</code>
     * @param value The bytes for destinationNumDoc to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationNumDocBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      destinationNumDoc_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object transactionValue_ = "";
    /**
     * <code>string transactionValue = 5;</code>
     * @return The transactionValue.
     */
    public java.lang.String getTransactionValue() {
      java.lang.Object ref = transactionValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transactionValue = 5;</code>
     * @return The bytes for transactionValue.
     */
    public com.google.protobuf.ByteString
        getTransactionValueBytes() {
      java.lang.Object ref = transactionValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transactionValue = 5;</code>
     * @param value The transactionValue to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionValue_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string transactionValue = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionValue() {
      transactionValue_ = getDefaultInstance().getTransactionValue();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string transactionValue = 5;</code>
     * @param value The bytes for transactionValue to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionValue_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:message.Transaction)
  }

  // @@protoc_insertion_point(class_scope:message.Transaction)
  private static final com.example.demo.message.Transaction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.message.Transaction();
  }

  public static com.example.demo.message.Transaction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Transaction>
      PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
    @java.lang.Override
    public Transaction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Transaction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Transaction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.message.Transaction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

