// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trasaction.proto
// Protobuf Java Version: 4.27.2

package com.example.demo.message;

public final class TransactionProto {
  private TransactionProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      TransactionProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_TransactionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_TransactionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020trasaction.proto\022\007message\"\205\001\n\013Transact" +
      "ion\022\022\n\nsourceName\030\001 \001(\t\022\024\n\014sourceNumDoc\030" +
      "\002 \001(\t\022\027\n\017destinationName\030\003 \001(\t\022\031\n\021destin" +
      "ationNumDoc\030\004 \001(\t\022\030\n\020transactionValue\030\005 " +
      "\001(\t\"&\n\020TransactionReply\022\022\n\nstatusCode\030\001 " +
      "\001(\t2m\n\037bankTransactionQueeBACENAdvisor\022J" +
      "\n\025sendSucessTransaction\022\024.message.Transa" +
      "ction\032\031.message.TransactionReply\"\000B4\n\030co" +
      "m.example.demo.messageB\020TransactionProto" +
      "P\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_Transaction_descriptor,
        new java.lang.String[] { "SourceName", "SourceNumDoc", "DestinationName", "DestinationNumDoc", "TransactionValue", });
    internal_static_message_TransactionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_TransactionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_TransactionReply_descriptor,
        new java.lang.String[] { "StatusCode", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
